version: '3'

services:
  # Trusted Server
  webapp:
    build:
      context: ./trustedserver
      dockerfile: Dockerfile
    container_name: csrf-webapp
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - ../trustedserver:/home/node
    networks:
      - bap-csrf-network

  # CSRF Exploit
  exploit:
    build:
      context: ./exploit
      dockerfile: Dockerfile
    container_name: csrf-exploit
    restart: unless-stopped
    tty: true
    ports:
      - "8082:8082"
    volumes:
      - ../exploit:/home/node
    networks:
      - bap-csrf-network

# Docker Networks
networks:
  bap-csrf-network:
    driver: bridge